# Site settings
author: Qiong Sun
title: Software Engineer
header-img: img/home-bg.png
email: joannesun44@gmail.com
copyright_name: Qiong Sun
description: > # this means to ignore newlines until "baseurl:"
  Why I want to become a software engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  joannesun44

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
